export const bankWalletAddress = `addr_test1qqqpda5lt3pl78u3neaukp35dmwrn6h047u6d40x995jfztp0hlge49v298ydlsgzvcfj4kdzftpxskprf8r30ux58cqptg3e4`;
//     name: "Mesh Token 00",
//     image: "ipfs://QmRzicpReutwCkM6aotuKjErFCUD213DpwPq6ByuzMJaua",
//     mediaType: "image/jpg",
//     description: "This NFT is minted by Mesh (https://meshjs.dev/).",
//   },
//   "1": {
//     name: "Mesh Token 01",
//     image: "ipfs://QmRzicpReutwCkM6aotuKjErFCUD213DpwPq6ByuzMJaua",
//     mediaType: "image/jpg",
//     description: "This NFT is minted by Mesh (https://meshjs.dev/).",
//   },
//   "2": {
//     name: "Mesh Token 02",
//     image: "ipfs://QmRzicpReutwCkM6aotuKjErFCUD213DpwPq6ByuzMJaua",
//     mediaType: "image/jpg",
//     description: "This NFT is minted by Mesh (https://meshjs.dev/).",
//   },
//   "3": {
//     name: "Mesh Token 03",
//     image: "ipfs://QmRzicpReutwCkM6aotuKjErFCUD213DpwPq6ByuzMJaua",
//     mediaType: "image/jpg",
//     description: "This NFT is minted by Mesh (https://meshjs.dev/).",
//   },
//   "4": {
//     name: "Mesh Token 04",
//     image: "ipfs://QmRzicpReutwCkM6aotuKjErFCUD213DpwPq6ByuzMJaua",
//     mediaType: "image/jpg",
//     description: "This NFT is minted by Mesh (https://meshjs.dev/).",
//   },
//   "5": {
//     name: "Mesh Token 05",
//     image: "ipfs://QmRzicpReutwCkM6aotuKjErFCUD213DpwPq6ByuzMJaua",
//     mediaType: "image/jpg",
//     description: "This NFT is minted by Mesh (https://meshjs.dev/).",
//   },
//   "6": {
//     name: "Mesh Token 06",
//     image: "ipfs://QmRzicpReutwCkM6aotuKjErFCUD213DpwPq6ByuzMJaua",
//     mediaType: "image/jpg",
//     description: "This NFT is minted by Mesh (https://meshjs.dev/).",
//   },
//   "7": {
//     name: "Mesh Token 07",
//     image: "ipfs://QmRzicpReutwCkM6aotuKjErFCUD213DpwPq6ByuzMJaua",
//     mediaType: "image/jpg",
//     description: "This NFT is minted by Mesh (https://meshjs.dev/).",
//   },
//   "8": {
//     name: "Mesh Token 08",
//     image: "ipfs://QmRzicpReutwCkM6aotuKjErFCUD213DpwPq6ByuzMJaua",
//     mediaType: "image/jpg",
//     description: "This NFT is minted by Mesh (https://meshjs.dev/).",
//   },
//   "9": {
//     name: "Mesh Token 09",
//     image: "ipfs://QmRzicpReutwCkM6aotuKjErFCUD213DpwPq6ByuzMJaua",
//     mediaType: "image/jpg",
//     description: "This NFT is minted by Mesh (https://meshjs.dev/).",
//   },
// };